[package]
name = "acidalia"
version = "0.0.1"
authors = ["telastrus <10052313+telastrus@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shaderc = "0.7"
#futures = "0.3"
iced_wgpu = { git = "https://github.com/hecrj/iced", version = "0.3" }
iced_winit = { git = "https://github.com/hecrj/iced", version = "0.2" }
derive_more = "0.99"

imgui-wgpu = "0.14"
imgui = "0.7"
imgui-winit-support = "0.7"

[patch.crates-io]
winit = { path = "../winit/" }