[package]
name = "acidalia"
version = "0.1.0"
authors = ["telastrus <10052313+telastrus@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#winit = "0.22"
shaderc = "0.6"
#futures = "0.3"
iced_wgpu = { git = "https://github.com/hecrj/iced" }
iced_winit = { git = "https://github.com/hecrj/iced" }
derive_more = "0.99"

#[dependencies.wgpu]
#version = "0.5"