[package]
name = "acidalia"
version = "0.0.1"
authors = ["telastrus <10052313+telastrus@users.noreply.github.com>"]
edition = "2018"
description = "The game's game engine's engine"
license = "MPL-2.0"
keywords = ["gamedev", "graphics", "game", "engine", "events"]
homepage = "https://github.com/tasgon/acidalia"
repository = "https://github.com/tasgon/acidalia"
documentation = "https://docs.rs/acidalia"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shaderc = "0.7"
futures = "0.3"
iced_wgpu = { git = "https://github.com/hecrj/iced", version = "0.3" }
iced_winit = { git = "https://github.com/hecrj/iced", version = "0.2" }
derive_more = "0.99"

imgui-wgpu = "0.14"
imgui = "0.7"
imgui-winit-support = "0.7"

egui = "0.8"
epi = "0.8"
egui_wgpu_backend = "0.4"
egui_winit_platform = "0.4"

lyon = "0.17"
bytemuck = "1.5"

#[patch.crates-io]
#winit = { path = "../winit/" }
