[package]
name = "acidalia"
version = "0.1.1"
authors = ["tasgon <tasgon_@outlook.com>"]
edition = "2018"
description = "The game's game engine's engine"
license = "MPL-2.0"
keywords = ["gamedev", "graphics", "game", "engine", "minimal"]
homepage = "https://github.com/tasgon/acidalia"
repository = "https://github.com/tasgon/acidalia"
documentation = "https://docs.rs/acidalia"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
iced = ["iced_wgpu", "iced_winit"]

[dependencies]
shaderc = "0.7"
futures = "0.3"
wgpu = "0.7"
winit = "0.24"
derive_more = "0.99"
bytemuck = "1.5"

iced_wgpu = { git = "https://github.com/hecrj/iced", version = "0.3", optional = true }
iced_winit = { git = "https://github.com/hecrj/iced", version = "0.2", optional = true }

imgui-wgpu = "0.14"
imgui = "0.7"
imgui-winit-support = "0.7"

#egui = "0.8"
#epi = "0.8"
#egui_wgpu_backend = "0.4"
#egui_winit_platform = "0.4"

#[patch.crates-io]
#winit = { path = "../winit/" }
